// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAjNtzpuE9s3PPZ85r2DiwEK5IAsr-t-E',
    appId: '1:657194860112:web:d2c633aa606563eb6c9b55',
    messagingSenderId: '657194860112',
    projectId: 'sagiro-app',
    authDomain: 'sagiro-app.firebaseapp.com',
    storageBucket: 'sagiro-app.firebasestorage.app',
    measurementId: 'G-DBPJR74NBJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP6ab0fx-FpPtzB67ojfYsN3Tt_p5riRA',
    appId: '1:657194860112:android:3bf06fa2efb82ec86c9b55',
    messagingSenderId: '657194860112',
    projectId: 'paisapilot-98642',
    storageBucket: 'paisapilot-98642.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARmhw0-k4O4WPKOzavjOhfTbkvoNx3dAI',
    appId: '1:657194860112:ios:37e2e8e73b5f9f6c6c9b55',
    messagingSenderId: '657194860112',
    projectId: 'sagiro-app',
    storageBucket: 'sagiro-app.firebasestorage.app',
    iosClientId:
        '657194860112-n1n7bdrkn7fe3ssf1go0fp5nc6tgv1er.apps.googleusercontent.com',
    iosBundleId: 'com.deshu.sagiro.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARmhw0-k4O4WPKOzavjOhfTbkvoNx3dAI',
    appId: '1:657194860112:ios:37e2e8e73b5f9f6c6c9b55',
    messagingSenderId: '657194860112',
    projectId: 'sagiro-app',
    storageBucket: 'sagiro-app.firebasestorage.app',
    iosClientId:
        '657194860112-n1n7bdrkn7fe3ssf1go0fp5nc6tgv1er.apps.googleusercontent.com',
    iosBundleId: 'com.deshu.sagiro.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAjNtzpuE9s3PPZ85r2DiwEK5IAsr-t-E',
    appId: '1:657194860112:web:ec8b3a1f36694a4b6c9b55',
    messagingSenderId: '657194860112',
    projectId: 'sagiro-app',
    authDomain: 'sagiro-app.firebaseapp.com',
    storageBucket: 'sagiro-app.firebasestorage.app',
    measurementId: 'G-TL2BWKHTDG',
  );
}
